name: CI

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container: continuumio/miniconda3:latest

    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: |
        pip install .
